version: "3.8"

services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    command: >
      mongod --auth

  app:
    build: .
    container_name: app_container
    ports:
      - "4000:3000"
    environment:
      APP_NAME: ${APP_NAME}
      DB_URI: ${DB_URI}
      PORT: ${PORT}
    depends_on:
      - mongo_db
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm start

volumes:
  mongo_data: {}
